# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &development
  adapter: mysql
  encoding: utf8
  database: AMCdev
  pool: 5
  username: root
  password: Leili@123
test: &test
  adapter: mysql
  encoding: utf8
  database: AMCtest
  pool: 5
  username: root
  password: Leili@123
production: &production
  adapter: mysql
  encoding: utf8
  database: AMCpro
  pool: 5
  username: root
  password: Leili@123


cucumber:
  <<: *test