
development:
  adapter: postgresql
  database: macrosoft_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: macrosoft_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: macrosoft_production
  pool: 5
  timeout: 5000